export enum CATAN_TILE_TYPES {
    WOOD = "wood",
    BRICK = "brick",
    SHEEP = "sheep",
    WHEAT = "wheat",
    ORE = "ore",
    DESERT = "desert"
}
export const BASE_CATAN_NUMBERS = [2, 3, 3, 4, 4, 5, 5, 6, 6, 8, 8, 9, 9, 10, 10, 11, 11, 12];

export const BASE_BOARD_LAYOUT = [2, 3, 4, 3, 2];

export const BASE_CATAN_TILES = [
    CATAN_TILE_TYPES.WOOD,
    CATAN_TILE_TYPES.WOOD,
    CATAN_TILE_TYPES.WOOD,
    CATAN_TILE_TYPES.WOOD,
    CATAN_TILE_TYPES.BRICK,
    CATAN_TILE_TYPES.BRICK,
    CATAN_TILE_TYPES.BRICK,
    CATAN_TILE_TYPES.SHEEP,
    CATAN_TILE_TYPES.SHEEP,
    CATAN_TILE_TYPES.SHEEP,
    CATAN_TILE_TYPES.SHEEP,
    CATAN_TILE_TYPES.WHEAT,
    CATAN_TILE_TYPES.WHEAT,
    CATAN_TILE_TYPES.WHEAT,
    CATAN_TILE_TYPES.WHEAT,
    CATAN_TILE_TYPES.ORE,
    CATAN_TILE_TYPES.ORE,
    CATAN_TILE_TYPES.ORE,
    CATAN_TILE_TYPES.DESERT
];


export const CATAN_TILE_COLORS: { [key in CATAN_TILE_TYPES]: string } = {
    [CATAN_TILE_TYPES.WOOD]: "#419141",
    [CATAN_TILE_TYPES.BRICK]: "#C55643",
    [CATAN_TILE_TYPES.SHEEP]: "#A5f25b",
    [CATAN_TILE_TYPES.WHEAT]: "#F6d33c",
    [CATAN_TILE_TYPES.ORE]: "#C9c9c8",
    [CATAN_TILE_TYPES.DESERT]: "#E8cfa0"
};
